name: build-apk-squircle-ce
 
on:
  workflow_dispatch:
  workflow_call:
 
env:
  JDK_VERSION: '17'
  ANDROID_COMPILE_SDK: '36'
  ANDROID_BUILD_TOOLS: '36.0.0'
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
 
permissions:
  contents: write
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clean runner environment
        run: |
          rm -rf ~/.gradle/caches/
          rm -rf ~/.gradle/daemon/
          rm -rf ~/.android/build-cache/
          rm -rf .gradle
 
      - name: Checkout source repo
        uses: actions/checkout@main
        with:
          repository: massivemadness/Squircle-CE
          ref: master
          path: squircle_ce_source
          fetch-depth: 0
          submodules: recursive
 
      - name: Checkout ci source repo (self)
        uses: actions/checkout@main
        with:
          path: ci_source
 
      - name: Initialization values
        run: |
          echo "BUILD_DATE=$(TZ=UTC-8 date +"%y.%m.%d-%H.%M.%S")" >> $GITHUB_ENV
 
      - name: Setup java 17
        uses: actions/setup-java@main
        with:
          java-version: "${{ env.JDK_VERSION }}"
          distribution: 'temurin'
 
      - name: Decode keystore.p12 and write signing.properties
        working-directory: ./squircle_ce_source
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > app/keystore.p12
          cat << EOF > local.properties
          KEYSTORE_PATH=${{ github.workspace }}/squircle_ce_source/app/keystore.p12
          KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS=${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD=${{ secrets.KEY_ALIAS_PASSWORD }}
          EOF
 
      # ======================================================================
      # 我只改这里！！！
      # 完全跟作者官方 GMS CI 一样：只保留 --no-configuration-cache
      # 删掉我之前错加的 --no-daemon --no-build-cache
      # ======================================================================
      - name: Build apk
        working-directory: ./squircle_ce_source
        run: | 
          chmod +x ./gradlew
          ./gradlew clean
          ./gradlew :app:assembleGmsRelease --no-configuration-cache
 
      - name: List generated apk and rename
        working-directory: ./squircle_ce_source
        run: |
          echo "Generated APK files:"
          find app/build/outputs -name "*.apk" -exec ls -lh {} \;
          mkdir -p ${{ github.workspace }}/dist
