name: build-apk-bv-fantasytyx
 
on:
  workflow_dispatch:
  workflow_call:
 
env:
  JDK_VERSION: '21'
  ANDROID_COMPILE_SDK: '36'
  ANDROID_BUILD_TOOLS: '36.0.0'
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
permissions:
  contents: write
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clean runner environment
        run: |
          rm -rf ~/.gradle/caches/
          rm -rf ~/.gradle/daemon/
          rm -rf ~/.android/build-cache/
          rm -rf .gradle
 
      - name: Checkout source repo (bv)
        uses: actions/checkout@main
        with:
          repository: fantasytyx/bv
          ref: develop
          path: bv_source
          fetch-depth: 0
          submodules: recursive
 
      - name: Checkout ci source repo (self)
        uses: actions/checkout@main
        with:
          path: ci_source
 
      - name: Initialization values
        run: |
          echo "BUILD_DATE=$(TZ=UTC-8 date +"%y.%m.%d-%H.%M.%S")" >> $GITHUB_ENV
 
      - name: Setup java
        uses: actions/setup-java@main
        with:
          java-version: "${{ env.JDK_VERSION }}"
          distribution: "temurin"
 
      - name: Set up python 3.12
        uses: actions/setup-python@main
        with:
          python-version: '3.12'
 
      - name: Customize scripts
        run: |
          chmod +x "${{ github.workspace }}/ci_source/scripts/customize-bv-fantasy.sh"
          "${{ github.workspace }}/ci_source/scripts/customize-bv-fantasy.sh"
 
      - name: Decode keystore
        working-directory: ./bv_source
        run: |
          mkdir -p keystore
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > keystore/release.keystore
 
      - name: Build release apk
        working-directory: ./bv_source
        env:
          RELEASE_STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          RELEASE_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          chmod +x ./gradlew
          ./gradlew :player:tv:assembleRelease --refresh-dependencies --no-daemon
          ./gradlew :app:assembleRelease --no-daemon --stacktrace
 
      - name: Rename and move apk
        working-directory: ./bv_source
        run: |
          mkdir -p "${{ github.workspace }}/dist"
          mv "./app/build/outputs/apk/default/release/BV"*"release_default_universal.apk" "${{ github.workspace }}/dist/fantasybv-${{ env.BUILD_DATE }}.apk"
 
      - name: Erase keystore, encrypt package and create release
        uses: ./ci_source/.github/actions/erase_aes256pac_release/
        with:
          P12_KEYSTORE_PATH: "./bv_source/keystore/release.keystore"
          ZIP_AES256_PWD: ${{ secrets.ZIP_AES256_PWD }}
          BUILD_ARTIFACT_PATH: "./dist/fantasybv-${{ env.BUILD_DATE }}.apk"
          RELEASE_TAG_NAME: "${{ env.BUILD_DATE }}-fantasybv"