name: build-apk-gkd

on:
  workflow_dispatch:
  workflow_call:

env:
  JDK_VERSION: '21'
  ANDROID_COMPILE_SDK: '36'
  ANDROID_BUILD_TOOLS: '36.0.0'
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clean runner environment
        run: |
          rm -rf ~/.gradle/caches/
          rm -rf ~/.gradle/daemon/
          rm -rf ~/.android/build-cache/
          rm -rf .gradle

      - name: Checkout source repo
        uses: actions/checkout@main
        with:
          repository: gkd-kit/gkd
          ref: main
          path: gkd_source
          fetch-depth: 0
          submodules: recursive

      - name: Checkout ci source repo (self)
        uses: actions/checkout@main
        with:
          path: ci_source

      - name: Initialization values
        run: |
          echo "BUILD_DATE=$(TZ=UTC-8 date +"%y.%m.%d-%H.%M.%S")" >> $GITHUB_ENV

      - name: Setup java
        uses: actions/setup-java@main
        with:
          distribution: 'temurin'
          java-version: '${{ env.JDK_VERSION }}'

      - name: Write keystore info
        working-directory: ./gkd_source
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > ${{ github.workspace }}/gkd_source/gkd.p12
          echo "GKD_STORE_FILE=${{ github.workspace }}/gkd_source/gkd.p12" >> gradle.properties
          echo "GKD_STORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> gradle.properties
          echo "GKD_KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> gradle.properties
          echo "GKD_KEY_PASSWORD=${{ secrets.KEY_ALIAS_PASSWORD }}" >> gradle.properties

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@main
        with:
          dependency-graph: generate-and-submit
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"

      - name: Build with gradle
        working-directory: ./gkd_source
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses > /dev/null || true
          echo 'android.sdk.channel=3' >> gradle.properties
          echo 'android.native.buildOutput=verbose' >> gradle.properties
          echo 'org.gradle.caching=true' >> gradle.properties
          echo 'org.gradle.parallel=true' >> gradle.properties
          chmod +x ./gradlew
          ./gradlew app:assembleGkdRelease

      - name: Rename and move
        working-directory: ./gkd_source
        run: |
          mkdir -p "${{ github.workspace }}/dist"
          apkPath=$(ls app/build/outputs/apk/gkd/release/app-gkd-release.apk)
          mv "$apkPath" "${{ github.workspace }}/dist/gkd-${{ env.BUILD_DATE }}.apk"

      - name: Erase keystore, encrypt package and create release
        uses: ./ci_source/.github/actions/erase_aes256pac_release/
        with:
          P12_KEYSTORE_PATH: "./gkd_source/gkd.p12"
          ZIP_AES256_PWD: ${{ secrets.ZIP_AES256_PWD }}
          BUILD_ARTIFACT_PATH: "./dist/gkd-${{ env.BUILD_DATE }}.apk"
          RELEASE_TAG_NAME: "${{ env.BUILD_DATE }}-gkd"