name: build-apk-bv-frost819
 
on:
  workflow_dispatch:
  workflow_call:
 
env:
  JDK_VERSION: '21'
  ANDROID_COMPILE_SDK: '36'
  ANDROID_BUILD_TOOLS: '36.0.0'
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
permissions:
  contents: write
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clean runner environment
        run: |
          rm -rf ~/.gradle/caches/
          rm -rf ~/.gradle/daemon/
          rm -rf ~/.android/build-cache/
          rm -rf .gradle
 
      - name: Checkout source repo (bv)
        uses: actions/checkout@main
        with:
          repository: Frost819/bv
          ref: feature
          path: bv_source
          fetch-depth: 0
          submodules: recursive
 
      - name: Checkout ci source repo (self)
        uses: actions/checkout@main
        with:
          path: ci_source
 
      - name: Initialization values
        run: |
          echo "BUILD_DATE=$(TZ=UTC-8 date +"%y.%m.%d-%H.%M.%S")" >> $GITHUB_ENV
 
      - name: Setup java
        uses: actions/setup-java@main
        with:
          java-version: "${{ env.JDK_VERSION }}"
          distribution: "temurin"

      - name: Decode and write release keystore
        working-directory: ./bv_source
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > keystore.p12
          # 创建一个虚拟的debug密钥库文件
          # 复制，确保是一个有效的文件
          cp keystore.p12 debug.keystore

      - name: Write signing.properties for release build
        working-directory: ./bv_source
        run: |
          cat << EOF > signing.properties
          releaseStoreFile=keystore.p12
          releaseKeyAlias=${{ secrets.KEY_ALIAS }}
          releaseStorePassword=${{ secrets.KEYSTORE_PASSWORD }}
          releaseKeyPassword=${{ secrets.KEY_ALIAS_PASSWORD }}
          # 提供虚拟且有效的DEBUG签名配置（用于绕过脚本检查）
          debugStoreFile=debug.keystore
          debugKeyAlias=androiddebugkey
          debugStorePassword=android
          debugKeyPassword=android
          EOF

      - name: Build release apk
        working-directory: ./bv_source
        run: |
          chmod +x ./gradlew
          # 构建主应用的 release 变体（会生成所有 flavor 的 APK，包括 TV 和 Mobile）
          ./gradlew :app:assembleRelease
 
      - name: Rename and move apk
        working-directory: ./bv_source
        run: |
          mkdir -p "${{ github.workspace }}/dist"
          mv "./app/build/outputs/apk/default/release/BV"*"release_default_universal.apk" "${{ github.workspace }}/dist/f819bv-${{ env.BUILD_DATE }}.apk"
 
      - name: Erase keystore, encrypt package and create release
        uses: ./ci_source/.github/actions/erase_aes256pac_release/
        with:
          P12_KEYSTORE_PATH: "./bv_source/keystore/release.keystore"
          ZIP_AES256_PWD: ${{ secrets.ZIP_AES256_PWD }}
          BUILD_ARTIFACT_PATH: "./dist/f819bv-${{ env.BUILD_DATE }}.apk"
          RELEASE_TAG_NAME: "${{ env.BUILD_DATE }}-f819bv"