name: build-apk-shizuku
 
on:
  workflow_dispatch:
  workflow_call:
 
env:
  JDK_VERSION: '21'
  ANDROID_COMPILE_SDK: '36'
  ANDROID_BUILD_TOOLS: '36.0.0'
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clean runner environment
        run: |
          # 清理可能存在的全局缓存文件
          rm -rf ~/.gradle/caches/
          rm -rf ~/.gradle/daemon/
          rm -rf ~/.android/build-cache/
          rm -rf .gradle
 
      - name: Checkout source repo
        uses: actions/checkout@main
        with:
          repository: RikkaApps/Shizuku
          ref: master
          path: shizuku_source
          fetch-depth: 0
          submodules: recursive
 
      - name: Checkout ci source repo (self)
        uses: actions/checkout@main
        with:
          path: ci_source

      - name: Setup java
        uses: actions/setup-java@main
        with:
          distribution: 'temurin'
          java-version: '${{ env.JDK_VERSION }}'
 
      - name: Write key
        working-directory: ./shizuku_source
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > key.p12
          echo "KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" > signing.properties
          echo "KEYSTORE_ALIAS=${{ secrets.KEY_ALIAS }}" >> signing.properties
          echo "KEYSTORE_ALIAS_PASSWORD=${{ secrets.KEY_ALIAS_PASSWORD }}" >> signing.properties
          echo "KEYSTORE_FILE=key.p12" >> signing.properties

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@main
        with:
          dependency-graph: generate-and-submit
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"
 
      - name: Build with gradle
        working-directory: ./shizuku_source
        id: buildWithGradle
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses > /dev/null || true
          echo 'android.sdk.channel=3' >> gradle.properties
          echo 'android.native.buildOutput=verbose' >> gradle.properties
          echo 'org.gradle.caching=true' >> gradle.properties
          echo 'org.gradle.parallel=true' >> gradle.properties
          chmod +x ./gradlew
          # ./gradlew :manager:assembleRelease
          # releaseName=`ls manager/build/outputs/apk/release/shizuku*-v*-release.apk | awk -F '(/|-release.apk)' '{print $6}'` && echo "releaseName=$releaseName" >> $GITHUB_OUTPUT
          ./gradlew assembleRelease
          releaseName=`ls build/outputs/apk/release/shizuku*-v*-release.apk | awk -F '(/|-release.apk)' '{print $6}'` && echo "releaseName=$releaseName" >> $GITHUB_OUTPUT
          echo '$releaseName'